/**
 * CustodyReportExport.tsx — Court-ready PDF export of the chain-of-custody.
 *
 * Uses @react-pdf/renderer to generate a formatted PDF containing:
 *   - Header with case number and document title
 *   - Report metadata (generated by, timestamp, classification)
 *   - Full custody timeline table
 *   - Hash verification status per entry
 *   - Footer with verification instructions and page numbers
 */

import React, { useState } from "react";
import {
  Document as PDFDocument,
  Page,
  Text,
  View,
  StyleSheet,
  pdf,
} from "@react-pdf/renderer";
import { Download, Loader2 } from "lucide-react";
import { format } from "date-fns";
import type {
  ChainOfCustodyEntry,
  Document as DocType,
} from "../types";

// ── PDF Styles ────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 9,
    fontFamily: "Helvetica",
    color: "#1a1a1a",
  },
  header: {
    borderBottomWidth: 2,
    borderBottomColor: "#0f172a",
    borderBottomStyle: "solid",
    paddingBottom: 8,
    marginBottom: 12,
  },
  title: { fontSize: 14, fontWeight: "bold", textTransform: "uppercase" },
  subtitle: { fontSize: 10, color: "#475569", marginTop: 2 },
  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 3,
    fontSize: 8,
    color: "#64748b",
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: "bold",
    marginTop: 14,
    marginBottom: 6,
    color: "#0f172a",
    textTransform: "uppercase",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    borderBottomStyle: "solid",
    paddingBottom: 3,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f1f5f9",
    borderBottomWidth: 1,
    borderBottomColor: "#cbd5e1",
    borderBottomStyle: "solid",
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "#e2e8f0",
    borderBottomStyle: "solid",
    paddingVertical: 3,
    paddingHorizontal: 2,
  },
  col1: { width: "6%", fontSize: 8 },
  col2: { width: "14%", fontSize: 7 },
  col3: { width: "10%", fontSize: 8 },
  col4: { width: "16%", fontSize: 8 },
  col5: { width: "12%", fontSize: 7 },
  col6: { width: "12%", fontSize: 7 },
  col7: { width: "20%", fontSize: 6, fontFamily: "Courier" },
  col8: { width: "10%", fontSize: 7 },
  thText: { fontWeight: "bold", color: "#334155", fontSize: 7 },
  footer: {
    position: "absolute",
    bottom: 25,
    left: 40,
    right: 40,
    fontSize: 7,
    color: "#94a3b8",
    textAlign: "center",
    borderTopWidth: 0.5,
    borderTopColor: "#e2e8f0",
    borderTopStyle: "solid",
    paddingTop: 5,
  },
  pageNumber: {
    position: "absolute",
    bottom: 25,
    right: 40,
    fontSize: 7,
    color: "#94a3b8",
  },
  verified: { color: "#16a34a" },
  mismatch: { color: "#dc2626", fontWeight: "bold" },
});

// ── PDF Document Component ────────────────────────────────────────────────────

interface CustodyReportProps {
  document: DocType;
  entries: ChainOfCustodyEntry[];
  generatedBy: string;
}

const CustodyReportPDF: React.FC<CustodyReportProps> = ({
  document: doc,
  entries,
  generatedBy,
}) => {
  const sorted = [...entries].sort(
    (a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime()
  );
  const now = format(new Date(), "dd MMM yyyy HH:mm:ss 'UTC'");

  return (
    <PDFDocument title={`Chain of Custody Report — ${doc.title}`} author="Secure Legal DMS">
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>Chain of Custody Report</Text>
          <Text style={styles.subtitle}>{doc.title}</Text>
        </View>

        {/* Metadata */}
        <View style={styles.metaRow}>
          <Text>Case Number: {doc.case_number}</Text>
          <Text>Classification: {doc.classification_level}</Text>
        </View>
        <View style={styles.metaRow}>
          <Text>Document Type: {doc.doc_type.replace(/_/g, " ")}</Text>
          <Text>Document ID: {doc.id}</Text>
        </View>
        <View style={styles.metaRow}>
          <Text>Generated By: {generatedBy}</Text>
          <Text>Generated At: {now}</Text>
        </View>
        <View style={styles.metaRow}>
          <Text>Total Custody Events: {sorted.length}</Text>
          <Text>Workflow Status: {doc.workflow_status}</Text>
        </View>

        {/* Custody Table */}
        <Text style={styles.sectionTitle}>Custody Events</Text>

        {/* Table header */}
        <View style={styles.tableHeader}>
          <Text style={{ ...styles.col1, ...styles.thText }}>#</Text>
          <Text style={{ ...styles.col2, ...styles.thText }}>Date/Time (UTC)</Text>
          <Text style={{ ...styles.col3, ...styles.thText }}>Action</Text>
          <Text style={{ ...styles.col4, ...styles.thText }}>Performed By</Text>
          <Text style={{ ...styles.col5, ...styles.thText }}>From</Text>
          <Text style={{ ...styles.col6, ...styles.thText }}>To</Text>
          <Text style={{ ...styles.col7, ...styles.thText }}>Hash at Action</Text>
          <Text style={{ ...styles.col8, ...styles.thText }}>Status</Text>
        </View>

        {/* Table rows */}
        {sorted.map((entry, idx) => (
          <View key={entry.id} style={styles.tableRow}>
            <Text style={styles.col1}>{idx + 1}</Text>
            <Text style={styles.col2}>
              {format(new Date(entry.timestamp), "dd/MM/yyyy HH:mm:ss")}
            </Text>
            <Text style={styles.col3}>{entry.action}</Text>
            <Text style={styles.col4}>
              {entry.performed_by_name}
              {entry.performed_by_badge_id ? ` (#${entry.performed_by_badge_id})` : ""}
            </Text>
            <Text style={styles.col5}>{entry.from_user_name ?? "—"}</Text>
            <Text style={styles.col6}>{entry.to_user_name ?? "—"}</Text>
            <Text style={styles.col7}>{entry.hash_at_action}</Text>
            <Text style={entry.hash_verified === false ? { ...styles.col8, ...styles.mismatch } : { ...styles.col8, ...styles.verified }}>
              {entry.hash_verified === true
                ? "VERIFIED"
                : entry.hash_verified === false
                ? "MISMATCH!"
                : "PENDING"}
            </Text>
          </View>
        ))}

        {/* Footer */}
        <Text style={styles.footer}>
          This report was generated from the Secure Digital Document Management System.
          Verify hashes against the system for authenticity. This document is not digitally signed.
        </Text>
        <Text
          style={styles.pageNumber}
          render={({ pageNumber, totalPages }) =>
            `Page ${pageNumber} of ${totalPages}`
          }
          fixed
        />
      </Page>
    </PDFDocument>
  );
};

// ── Export Button Component ───────────────────────────────────────────────────

interface ExportButtonProps {
  document: DocType;
  entries: ChainOfCustodyEntry[];
  generatedBy: string;
}

export const CustodyReportExport: React.FC<ExportButtonProps> = ({
  document: doc,
  entries,
  generatedBy,
}) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleExport() {
    setLoading(true);
    setError(null);
    try {
      const blob = await pdf(
        <CustodyReportPDF
          document={doc}
          entries={entries}
          generatedBy={generatedBy}
        />
      ).toBlob();
      const url = URL.createObjectURL(blob);
      const a = window.document.createElement("a");
      a.href = url;
      a.download = `custody_report_${doc.case_number}_${format(new Date(), "yyyyMMdd_HHmmss")}.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      setError("Failed to generate PDF. Please try again.");
      console.error("PDF generation error:", err);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="inline-flex items-center gap-2">
      <button
        onClick={handleExport}
        disabled={loading || entries.length === 0}
        className="inline-flex items-center gap-1.5 rounded-xl border border-[#E7E3DA] bg-white px-3.5 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-50 transition-colors shadow-sm disabled:cursor-not-allowed disabled:opacity-50"
        aria-label="Export chain of custody report as PDF"
      >
        {loading ? (
          <>
            <Loader2 className="h-3.5 w-3.5 animate-spin text-[#EAA037]" aria-hidden="true" />
            <span>Generating PDF…</span>
          </>
        ) : (
          <>
            <Download className="h-3.5 w-3.5 text-slate-500" aria-hidden="true" />
            <span>Export Custody PDF</span>
          </>
        )}
      </button>
      {error && <span className="text-xs text-red-600" role="alert">{error}</span>}
    </div>
  );
};
