import {
  AuditResult,
  CaseStatus,
  ClassificationLevel,
  CustodyAction,
  DocType,
  UserRole,
  type AuditLogEntry,
  type Case,
  type ChainOfCustodyEntry,
  type Document,
  type DocumentVersion,
  type Role,
  type SearchFacets,
  type WorkflowConfig,
} from "../types";


export interface MockUser {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  badge_id: string;
  department: string;
  department_id: string;
  max_classification: ClassificationLevel;
}

export const MOCK_USERS: Record<UserRole, MockUser> = {
  [UserRole.SUPER_ADMIN]: {
    id: "u-001",
    name: "Vikram Malhotra",
    email: "vikram.admin@gov.in",
    role: UserRole.SUPER_ADMIN,
    badge_id: "SA-9012",
    department: "System Administration",
    department_id: "d0000001-0000-0000-0000-000000000006",
    max_classification: ClassificationLevel.SECRET,
  },
  [UserRole.INVESTIGATING_OFFICER]: {
    id: "u-002",
    name: "Inspector Rajesh Sharma",
    email: "rajesh.sharma@police.gov.in",
    role: UserRole.INVESTIGATING_OFFICER,
    badge_id: "IO-4421",
    department: "Cyber Crime Unit",
    department_id: "d0000001-0000-0000-0000-000000000002",
    max_classification: ClassificationLevel.CONFIDENTIAL,
  },
  [UserRole.SUPERVISOR]: {
    id: "u-003",
    name: "ACP Ananya Roy",
    email: "ananya.roy@police.gov.in",
    role: UserRole.SUPERVISOR,
    badge_id: "SUP-1088",
    department: "Police Headquarters",
    department_id: "d0000001-0000-0000-0000-000000000001",
    max_classification: ClassificationLevel.SECRET,
  },
  [UserRole.PROSECUTOR]: {
    id: "u-004",
    name: "Adv. Meera Sen",
    email: "meera.sen@prosecution.gov.in",
    role: UserRole.PROSECUTOR,
    badge_id: "PRO-7731",
    department: "District Prosecution Office",
    department_id: "d0000001-0000-0000-0000-000000000003",
    max_classification: ClassificationLevel.CONFIDENTIAL,
  },
  [UserRole.FORENSIC_ANALYST]: {
    id: "u-005",
    name: "Dr. K. S. Murthy",
    email: "ks.murthy@fsl.gov.in",
    role: UserRole.FORENSIC_ANALYST,
    badge_id: "FSL-3309",
    department: "Forensic Science Laboratory",
    department_id: "d0000001-0000-0000-0000-000000000004",
    max_classification: ClassificationLevel.CONFIDENTIAL,
  },
  [UserRole.COURT_CLERK]: {
    id: "u-006",
    name: "Prakash Joshi",
    email: "prakash.joshi@court.gov.in",
    role: UserRole.COURT_CLERK,
    badge_id: "CLK-1102",
    department: "District Court",
    department_id: "d0000001-0000-0000-0000-000000000005",
    max_classification: ClassificationLevel.RESTRICTED,
  },
  [UserRole.AUDITOR]: {
    id: "u-007",
    name: "Suresh Menon",
    email: "suresh.menon@audit.gov.in",
    role: UserRole.AUDITOR,
    badge_id: "AUD-5520",
    department: "Independent Judicial Oversight",
    department_id: "d0000001-0000-0000-0000-000000000006",
    max_classification: ClassificationLevel.SECRET,
  },
  [UserRole.DEPT_ADMIN]: {
    id: "u-008",
    name: "Kavita Rao",
    email: "kavita.rao@police.gov.in",
    role: UserRole.DEPT_ADMIN,
    badge_id: "DA-2041",
    department: "Police Headquarters",
    department_id: "d0000001-0000-0000-0000-000000000001",
    max_classification: ClassificationLevel.SECRET,
  },
  [UserRole.EXTERNAL_COUNSEL]: {
    id: "u-009",
    name: "Adv. David Vance",
    email: "david.vance@chambers.law",
    role: UserRole.EXTERNAL_COUNSEL,
    badge_id: "EXT-8001",
    department: "External Legal Counsel",
    department_id: "d0000001-0000-0000-0000-000000000005",
    max_classification: ClassificationLevel.RESTRICTED,
  },
};

export const MOCK_ROLES: Role[] = [
  {
    id: "r0000001-0000-0000-0000-000000000001",
    name: UserRole.SUPER_ADMIN,
    description: "Full system administrator with unrestricted access",
    permissions_json: {
      allowed_doc_types: Object.values(DocType),
      allowed_actions: ["VIEW", "DOWNLOAD", "PRINT", "EDIT", "TRANSFER", "FULL"],
      max_classification: "SECRET",
      can_manage_users: true,
      can_manage_cases: true,
      can_manage_access: true,
      can_view_audit_logs: true,
      can_approve_workflows: true,
      is_time_boxed: false,
      default_access_duration_days: null,
      redacted_fields: [],
    },
  },
  {
    id: "r0000001-0000-0000-0000-000000000003",
    name: UserRole.INVESTIGATING_OFFICER,
    description: "Police investigating officer — manages FIRs, evidence, and case documents",
    permissions_json: {
      allowed_doc_types: ["FIR", "CHARGE_SHEET", "WITNESS_STATEMENT", "EVIDENCE_PHOTO", "MEMO", "OTHER"],
      allowed_actions: ["VIEW", "DOWNLOAD", "PRINT", "EDIT", "TRANSFER"],
      max_classification: "CONFIDENTIAL",
      can_manage_users: false,
      can_manage_cases: true,
      can_manage_access: false,
      can_view_audit_logs: false,
      can_approve_workflows: false,
      is_time_boxed: false,
      default_access_duration_days: null,
      redacted_fields: ["informant_id"],
    },
  },
  {
    id: "r0000001-0000-0000-0000-000000000004",
    name: UserRole.SUPERVISOR,
    description: "Senior officer supervising investigations and approving documents",
    permissions_json: {
      allowed_doc_types: Object.values(DocType),
      allowed_actions: ["VIEW", "DOWNLOAD", "PRINT", "EDIT", "TRANSFER"],
      max_classification: "SECRET",
      can_manage_users: false,
      can_manage_cases: true,
      can_manage_access: true,
      can_view_audit_logs: true,
      can_approve_workflows: true,
      is_time_boxed: false,
      default_access_duration_days: null,
      redacted_fields: [],
    },
  },
  {
    id: "r0000001-0000-0000-0000-000000000007",
    name: UserRole.COURT_CLERK,
    description: "Court clerk managing case filings and court orders",
    permissions_json: {
      allowed_doc_types: ["CHARGE_SHEET", "COURT_ORDER", "LEGAL_BRIEF", "FIR"],
      allowed_actions: ["VIEW", "DOWNLOAD", "PRINT"],
      max_classification: "RESTRICTED",
      can_manage_users: false,
      can_manage_cases: false,
      can_manage_access: false,
      can_view_audit_logs: false,
      can_approve_workflows: false,
      is_time_boxed: false,
      default_access_duration_days: null,
      redacted_fields: ["witness_name", "informant_id", "victim_details", "suspect_address"],
    },
  },
  {
    id: "r0000001-0000-0000-0000-000000000008",
    name: UserRole.AUDITOR,
    description: "Read-only auditor with access to all data and audit logs for compliance review",
    permissions_json: {
      allowed_doc_types: Object.values(DocType),
      allowed_actions: ["VIEW"],
      max_classification: "SECRET",
      can_manage_users: false,
      can_manage_cases: false,
      can_manage_access: false,
      can_view_audit_logs: true,
      can_approve_workflows: false,
      is_time_boxed: false,
      default_access_duration_days: null,
      redacted_fields: [],
    },
  },
];

export const MOCK_CASES: Case[] = [
  {
    id: "c-001",
    case_number: "CR-2026-0892",
    fir_number: "FIR-449/2026",
    type: "FIR",
    status: CaseStatus.UNDER_INVESTIGATION,
    title: "State vs. Syndicate Financial Cyber-Heist",
    description: "Multi-layered corporate malware infiltration and unverified wire diversion totaling 4.2M USD.",
    jurisdiction: "Metropolitan Cyber Crime Bench",
    created_by: "u-002",
    created_at: "2026-08-12T09:30:00Z",
  },
  {
    id: "c-002",
    case_number: "CR-2026-1044",
    fir_number: "FIR-512/2026",
    type: "COMPLAINT",
    status: CaseStatus.CHARGE_SHEETED,
    title: "In re: Supply Chain Counterfeit Pharmaceutical Distribution",
    description: "Inter-state distribution network targeting critical hospital medication with forged inspection certificates.",
    jurisdiction: "Central Special Enforcement Division",
    created_by: "u-003",
    created_at: "2026-08-18T14:15:00Z",
  },
  {
    id: "c-003",
    case_number: "CR-2026-1180",
    fir_number: null,
    type: "SUO_MOTO",
    status: CaseStatus.IN_TRIAL,
    title: "State vs. Apex Infrastructure Bribery & Procurement Fraud",
    description: "Forensic audit of public tender collusion involving encrypted messaging transcripts and offshore shell entities.",
    jurisdiction: "Special Anti-Corruption Tribunal",
    created_by: "u-001",
    created_at: "2026-08-01T11:00:00Z",
  },
];

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: "doc-001",
    case_id: "c-001",
    doc_type: DocType.LEGAL_BRIEF,
    title: "Hearing transcript — March 2024",
    description: "Certified verbatim transcript of procedural hearing and cross-examination testimonies.",
    current_version_id: "ver-001-3",
    uploaded_by: "u-002",
    uploaded_by_name: "Mara Chen",
    uploaded_by_badge_id: "MC-9014",
    classification_level: ClassificationLevel.CONFIDENTIAL,
    workflow_status: "COURT_SUBMITTED",
    case_number: "CV-24-0187",
    created_at: "2024-03-22T14:30:00Z",
    updated_at: "2024-03-22T14:30:00Z",
  },
  {
    id: "doc-002",
    case_id: "c-001",
    doc_type: DocType.FORENSIC_REPORT,
    title: "Forensic accounting report",
    description: "Detailed financial ledger audit and ledger trace of unverified transaction streams.",
    current_version_id: "ver-002-1",
    uploaded_by: "u-005",
    uploaded_by_name: "Adrian Cole",
    uploaded_by_badge_id: "AC-4402",
    classification_level: ClassificationLevel.SECRET,
    workflow_status: "SUPERVISOR_APPROVED",
    case_number: "CV-24-0187",
    created_at: "2024-03-20T09:15:00Z",
    updated_at: "2024-03-20T09:15:00Z",
  },
  {
    id: "doc-003",
    case_id: "c-002",
    doc_type: DocType.MEMO,
    title: "Chain of custody log",
    description: "Physical evidence transfer and tamper-evident seal verification audit record.",
    current_version_id: "ver-003-2",
    uploaded_by: "u-002",
    uploaded_by_name: "Jon Bell",
    uploaded_by_badge_id: "JB-7719",
    classification_level: ClassificationLevel.RESTRICTED,
    workflow_status: "PEER_REVIEW",
    case_number: "CV-24-0114",
    created_at: "2024-03-18T16:00:00Z",
    updated_at: "2024-03-18T16:00:00Z",
  },
  {
    id: "doc-004",
    case_id: "c-003",
    doc_type: DocType.WITNESS_STATEMENT,
    title: "Witness statement — R. Alvarez",
    description: "Deposition statement recorded under affirmation regarding vendor kickback protocol.",
    current_version_id: "ver-004-1",
    uploaded_by: "u-006",
    uploaded_by_name: "Sarah Jenkins",
    uploaded_by_badge_id: "SJ-1108",
    classification_level: ClassificationLevel.CONFIDENTIAL,
    workflow_status: "SUBMITTED_FOR_REVIEW",
    case_number: "CV-23-0941",
    created_at: "2024-03-14T11:20:00Z",
    updated_at: "2024-03-14T11:20:00Z",
  },
  {
    id: "doc-005",
    case_id: "c-001",
    doc_type: DocType.FIR,
    title: "Digital Seizure & Exfiltration Report",
    description: "Initial registered complaint detailing unauthorized SSH tunneling and intrusion trace.",
    current_version_id: "ver-005-1",
    uploaded_by: "u-002",
    uploaded_by_name: "Mara Chen",
    uploaded_by_badge_id: "MC-9014",
    classification_level: ClassificationLevel.SECRET,
    workflow_status: "SUPERVISOR_APPROVED",
    case_number: "CV-24-0187",
    created_at: "2024-03-10T10:00:00Z",
    updated_at: "2024-03-12T16:20:00Z",
  },
  {
    id: "doc-006",
    case_id: "c-002",
    doc_type: DocType.COURT_ORDER,
    title: "Asset Preservation & WORM Seizure Order",
    description: "Judicial injunction mandating immutable electronic storage and custodian deposition.",
    current_version_id: "ver-006-1",
    uploaded_by: "u-006",
    uploaded_by_name: "Prakash Joshi",
    uploaded_by_badge_id: "CLK-1102",
    classification_level: ClassificationLevel.RESTRICTED,
    workflow_status: "COURT_SUBMITTED",
    case_number: "CV-24-0114",
    created_at: "2024-03-08T13:00:00Z",
    updated_at: "2024-03-08T13:00:00Z",
  },
];

export const MOCK_VERSIONS: Record<string, DocumentVersion[]> = {
  "doc-001": [
    {
      id: "ver-001-2",
      document_id: "doc-001",
      version_number: 2,
      file_path: "documents/c-001/doc-001/ver-001-2/FIR_Amended_Final.pdf",
      file_size_bytes: 482910,
      file_hash_sha256: "3f79a90e3864197e8c07629ef0bbbc094bb945d8b8a53e6b7235a96860d5b410",
      mime_type: "application/pdf",
      uploaded_by: "u-002",
      uploaded_by_name: "Inspector Rajesh Sharma",
      change_reason: "Incorporated authenticated server gateway logs and IP geolocation tables as Annexure C.",
      ocr_text: "FIRST INFORMATION REPORT (Under Section 154 Cr.P.C.)\nDistrict: Central | Police Station: Cyber Crime | Year: 2026\nFIR No: 449/2026 | Date: 12/08/2026\nComplainant: Apex FinTech Corp | Investigating Officer: Insp. Rajesh Sharma (#IO-4421)\nIncident Summary: Unauthorized SSH tunneling and brute-force key exchange detected on production cluster at 02:14 UTC.\nWitness Statement: Systems engineer observed unverified credential escalation.\nInformant Code: INF-88492\nSuspect Coordinates: Sector 62, Technology Park.",
      thumbnail_path: null,
      is_immutable: true,
      created_at: "2026-08-14T16:20:00Z",
    },
    {
      id: "ver-001-1",
      document_id: "doc-001",
      version_number: 1,
      file_path: "documents/c-001/doc-001/ver-001-1/FIR_Initial_Draft.pdf",
      file_size_bytes: 312040,
      file_hash_sha256: "a591a6d40bf420404a011733cfb7b190d62c65bf0bcda32b57b277d9ad9f146e",
      mime_type: "application/pdf",
      uploaded_by: "u-002",
      uploaded_by_name: "Inspector Rajesh Sharma",
      change_reason: "Initial submission of First Information Report.",
      ocr_text: "FIRST INFORMATION REPORT (Under Section 154 Cr.P.C.)\nDistrict: Central | Police Station: Cyber Crime | Year: 2026\nFIR No: 449/2026 | Date: 12/08/2026\nComplainant: Apex FinTech Corp | Investigating Officer: Insp. Rajesh Sharma (#IO-4421)\nIncident Summary: Unauthorized SSH tunneling detected on cluster.\nInformant Code: INF-88492.",
      thumbnail_path: null,
      is_immutable: true,
      created_at: "2026-08-12T10:00:00Z",
    },
  ],
  "doc-002": [
    {
      id: "ver-002-1",
      document_id: "doc-002",
      version_number: 1,
      file_path: "documents/c-001/doc-002/ver-002-1/FSL_Report_770.pdf",
      file_size_bytes: 2049100,
      file_hash_sha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      mime_type: "application/pdf",
      uploaded_by: "u-005",
      uploaded_by_name: "Dr. K. S. Murthy",
      change_reason: "Initial forensic laboratory report.",
      ocr_text: "GOVERNMENT FORENSIC SCIENCE LABORATORY\nCyber Forensics Division | Report Reference: FSL-2026-770\nEvidence Received: 1x NVMe M.2 1TB Solid State Drive, sealed with Tamper-Evident Tape #TET-9941\nAcquisition Hash: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 (SHA-256 MATCH)\nFindings: Unallocated space contained compiled C++ remote access trojan (RAT) configured with command and control domain pool.",
      thumbnail_path: null,
      is_immutable: true,
      created_at: "2026-08-16T11:45:00Z",
    },
  ],
  "doc-003": [
    {
      id: "ver-003-3",
      document_id: "doc-003",
      version_number: 3,
      file_path: "documents/c-002/doc-003/ver-003-3/ChargeSheet_Approved_CourtCopy.pdf",
      file_size_bytes: 1420500,
      file_hash_sha256: "b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9",
      mime_type: "application/pdf",
      uploaded_by: "u-002",
      uploaded_by_name: "Inspector Rajesh Sharma",
      change_reason: "Prosecutor amendments accepted; final submission to Court Magistrate.",
      ocr_text: "IN THE COURT OF CHIEF JUDICIAL MAGISTRATE\nPOLICE CHARGE SHEET (Section 173 Cr.P.C.)\nState vs. Accused Persons #1 to #7\nOffences: 420 (Cheating), 468 (Forgery for Cheating), 120B (Criminal Conspiracy)\nList of Documents Filed: FIR Copy, Seizure Memos 1-14, FSL Chemical Reports, Bank Statements.",
      thumbnail_path: null,
      is_immutable: true,
      created_at: "2026-08-25T15:30:00Z",
    },
  ],
};

export const MOCK_CUSTODY: Record<string, ChainOfCustodyEntry[]> = {
  "doc-001": [
    {
      id: "coc-001",
      document_id: "doc-001",
      version_id: "ver-001-1",
      action: CustodyAction.UPLOADED,
      performed_by: "u-002",
      performed_by_name: "Inspector Rajesh Sharma",
      performed_by_role: UserRole.INVESTIGATING_OFFICER,
      performed_by_badge_id: "IO-4421",
      from_user: null,
      from_user_name: null,
      to_user: null,
      to_user_name: null,
      timestamp: "2026-08-12T10:00:00Z",
      hash_at_action: "a591a6d40bf420404a011733cfb7b190d62c65bf0bcda32b57b277d9ad9f146e",
      hash_verified: true,
      notes: "Uploaded initial FIR PDF from Station Terminal #4.",
    },
    {
      id: "coc-002",
      document_id: "doc-001",
      version_id: "ver-001-1",
      action: CustodyAction.VIEWED,
      performed_by: "u-003",
      performed_by_name: "ACP Ananya Roy",
      performed_by_role: UserRole.SUPERVISOR,
      performed_by_badge_id: "SUP-1088",
      from_user: null,
      from_user_name: null,
      to_user: null,
      to_user_name: null,
      timestamp: "2026-08-13T08:15:00Z",
      hash_at_action: "a591a6d40bf420404a011733cfb7b190d62c65bf0bcda32b57b277d9ad9f146e",
      hash_verified: true,
      notes: "Reviewed draft FIR prior to supervisory approval.",
    },
    {
      id: "coc-003",
      document_id: "doc-001",
      version_id: "ver-001-2",
      action: CustodyAction.UPLOADED,
      performed_by: "u-002",
      performed_by_name: "Inspector Rajesh Sharma",
      performed_by_role: UserRole.INVESTIGATING_OFFICER,
      performed_by_badge_id: "IO-4421",
      from_user: null,
      from_user_name: null,
      to_user: null,
      to_user_name: null,
      timestamp: "2026-08-14T16:20:00Z",
      hash_at_action: "3f79a90e3864197e8c07629ef0bbbc094bb945d8b8a53e6b7235a96860d5b410",
      hash_verified: true,
      notes: "Submitted revision v2 with Annexure C gateway logs.",
    },
    {
      id: "coc-004",
      document_id: "doc-001",
      version_id: "ver-001-2",
      action: CustodyAction.TRANSFERRED,
      performed_by: "u-003",
      performed_by_name: "ACP Ananya Roy",
      performed_by_role: UserRole.SUPERVISOR,
      performed_by_badge_id: "SUP-1088",
      from_user: "u-002",
      from_user_name: "Inspector Rajesh Sharma",
      to_user: "u-004",
      to_user_name: "Adv. Meera Sen",
      timestamp: "2026-08-15T11:00:00Z",
      hash_at_action: "3f79a90e3864197e8c07629ef0bbbc094bb945d8b8a53e6b7235a96860d5b410",
      hash_verified: true,
      notes: "Formally assigned case brief and verified documents to Public Prosecution.",
    },
  ],
};

export const MOCK_AUDIT_LOGS: Record<string, AuditLogEntry[]> = {
  "doc-001": [
    {
      id: 10401,
      event_id: "evt-001",
      user_id: "u-002",
      user_name: "Inspector Rajesh Sharma",
      action: "DOCUMENT_UPLOADED",
      resource_type: "DOCUMENT",
      resource_id: "doc-001",
      ip_address: "10.14.22.8",
      user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
      details: { version: 1, hash: "a591a6d40bf420404a011733cfb7b190d62c65bf0bcda32b57b277d9ad9f146e" },
      timestamp: "2026-08-12T10:00:00Z",
      result: AuditResult.SUCCESS,
      previous_log_hash: "0000000000000000000000000000000000000000000000000000000000000000",
      current_log_hash: "8f48a123689408b0821ad2f741544a4da7ebcc94708a3f81e3a9c7b988f57912",
    },
    {
      id: 10402,
      event_id: "evt-002",
      user_id: "u-003",
      user_name: "ACP Ananya Roy",
      action: "DOCUMENT_VIEWED",
      resource_type: "DOCUMENT",
      resource_id: "doc-001",
      ip_address: "10.14.10.4",
      user_agent: "Mozilla/5.0 (X11; Linux x86_64)",
      details: { section: "metadata_and_versions" },
      timestamp: "2026-08-13T08:15:00Z",
      result: AuditResult.SUCCESS,
      previous_log_hash: "8f48a123689408b0821ad2f741544a4da7ebcc94708a3f81e3a9c7b988f57912",
      current_log_hash: "32d847291a1820b92c4a928ef28292837190f84a800e84b8d91c78112e73a948",
    },
    {
      id: 10403,
      event_id: "evt-003",
      user_id: "u-002",
      user_name: "Inspector Rajesh Sharma",
      action: "DOCUMENT_VERSION_CREATED",
      resource_type: "DOCUMENT",
      resource_id: "doc-001",
      ip_address: "10.14.22.8",
      user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
      details: { version: 2, hash: "3f79a90e3864197e8c07629ef0bbbc094bb945d8b8a53e6b7235a96860d5b410" },
      timestamp: "2026-08-14T16:20:00Z",
      result: AuditResult.SUCCESS,
      previous_log_hash: "32d847291a1820b92c4a928ef28292837190f84a800e84b8d91c78112e73a948",
      current_log_hash: "557a2f90119e81b671b782910fa9024018281140029bfa81023a1a9e88b209fa",
    },
    {
      id: 10404,
      event_id: "evt-004",
      user_id: "u-003",
      user_name: "ACP Ananya Roy",
      action: "WORKFLOW_TRANSITION",
      resource_type: "DOCUMENT",
      resource_id: "doc-001",
      ip_address: "10.14.10.4",
      user_agent: "Mozilla/5.0 (X11; Linux x86_64)",
      details: { from_status: "SUBMITTED_FOR_REVIEW", to_status: "SUPERVISOR_APPROVED", workflow: "charge_sheet" },
      timestamp: "2026-08-15T11:00:00Z",
      result: AuditResult.SUCCESS,
      previous_log_hash: "557a2f90119e81b671b782910fa9024018281140029bfa81023a1a9e88b209fa",
      current_log_hash: "99104fae89201bd9230182901fabc489201948bb01948ae8829014bcda901842",
    },
  ],
};

export const MOCK_WORKFLOW_CONFIGS: WorkflowConfig[] = [
  {
    name: "charge_sheet",
    display_name: "Police Charge Sheet Workflow",
    description: "Standard statutory approval workflow for filing formal charge sheets in judicial courts.",
    states: [
      { name: "DRAFT", display_name: "Draft Under Preparation", is_initial: true, is_terminal: false, sla_hours: 48, escalation_role: "SUPERVISOR" },
      { name: "SUBMITTED_FOR_REVIEW", display_name: "Submitted for Supervisory Review", is_initial: false, is_terminal: false, sla_hours: 24, escalation_role: "SUPERVISOR" },
      { name: "SUPERVISOR_APPROVED", display_name: "Supervisor Approved", is_initial: false, is_terminal: false, sla_hours: 48, escalation_role: "PROSECUTOR" },
      { name: "PROSECUTOR_REVIEW", display_name: "Prosecutor Scrutiny", is_initial: false, is_terminal: false, sla_hours: 48, escalation_role: "PROSECUTOR" },
      { name: "COURT_SUBMITTED", display_name: "Filed in Court", is_initial: false, is_terminal: true, sla_hours: null, escalation_role: null },
      { name: "REJECTED", display_name: "Returned with Objections", is_initial: false, is_terminal: false, sla_hours: 24, escalation_role: "INVESTIGATING_OFFICER" },
      { name: "ARCHIVED", display_name: "Archived", is_initial: false, is_terminal: true, sla_hours: null, escalation_role: null },
    ],
    transitions: [
      { from_state: "DRAFT", to_state: "SUBMITTED_FOR_REVIEW", required_role: "INVESTIGATING_OFFICER", display_name: "Submit for Review", requires_comment: false },
      { from_state: "SUBMITTED_FOR_REVIEW", to_state: "SUPERVISOR_APPROVED", required_role: "SUPERVISOR", display_name: "Approve Charge Sheet", requires_comment: false },
      { from_state: "SUBMITTED_FOR_REVIEW", to_state: "REJECTED", required_role: "SUPERVISOR", display_name: "Return for Corrections", requires_comment: true },
      { from_state: "SUPERVISOR_APPROVED", to_state: "PROSECUTOR_REVIEW", required_role: "PROSECUTOR", display_name: "Initiate Legal Scrutiny", requires_comment: false },
      { from_state: "PROSECUTOR_REVIEW", to_state: "COURT_SUBMITTED", required_role: "PROSECUTOR", display_name: "File in Court", requires_comment: false },
      { from_state: "PROSECUTOR_REVIEW", to_state: "REJECTED", required_role: "PROSECUTOR", display_name: "Legal Defect Return", requires_comment: true },
      { from_state: "REJECTED", to_state: "DRAFT", required_role: "INVESTIGATING_OFFICER", display_name: "Reopen for Revision", requires_comment: false },
    ],
  },
  {
    name: "forensic_report",
    display_name: "Forensic Evidence Workflow",
    description: "Quality assurance and chain of custody validation for scientific lab evidence.",
    states: [
      { name: "DRAFT", display_name: "Analysis in Progress", is_initial: true, is_terminal: false, sla_hours: 72, escalation_role: "FORENSIC_ANALYST" },
      { name: "PEER_REVIEW", display_name: "Senior Analyst Verification", is_initial: false, is_terminal: false, sla_hours: 24, escalation_role: "FORENSIC_ANALYST" },
      { name: "DIRECTOR_SIGNED", display_name: "FSL Director Authorized", is_initial: false, is_terminal: false, sla_hours: 12, escalation_role: "SUPERVISOR" },
      { name: "SEALED", display_name: "Evidentiary Sealed & Delivered", is_initial: false, is_terminal: true, sla_hours: null, escalation_role: null },
    ],
    transitions: [
      { from_state: "DRAFT", to_state: "PEER_REVIEW", required_role: "FORENSIC_ANALYST", display_name: "Submit for Peer Review", requires_comment: false },
      { from_state: "PEER_REVIEW", to_state: "DIRECTOR_SIGNED", required_role: "SUPERVISOR", display_name: "Authorize Lab Report", requires_comment: false },
      { from_state: "DIRECTOR_SIGNED", to_state: "SEALED", required_role: "SUPERVISOR", display_name: "Seal & Dispatch to Court", requires_comment: false },
    ],
  },
];

export const MOCK_FACETS: SearchFacets = {
  case_types: { FIR: 2, COMPLAINT: 1, SUO_MOTO: 1, TRANSFER: 0, APPEAL: 0 },
  doc_types: {
    FIR: 1,
    CHARGE_SHEET: 1,
    FORENSIC_REPORT: 1,
    COURT_ORDER: 1,
    WITNESS_STATEMENT: 0,
    EVIDENCE_PHOTO: 0,
    LEGAL_BRIEF: 0,
    MEMO: 0,
    OTHER: 0,
  },
  case_statuses: {
    UNDER_INVESTIGATION: 1,
    CHARGE_SHEETED: 1,
    IN_TRIAL: 1,
    OPEN: 0,
    CLOSED: 0,
    ARCHIVED: 0,
  },
  classification_levels: {
    RESTRICTED: 2,
    CONFIDENTIAL: 1,
    SECRET: 1,
    UNCLASSIFIED: 0,
  },
};
